### ISSUE TITLE
Use of clusterName can be limiting in a few cases.

### ISSUE THREAD

**Issue by thedodd** [timescale/timescaledb-kubernetes#109]
The `clusterName` helper template [defined here](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/_helpers.tpl#L13-L15) which we are using in a few different locations, actually turns out to be a bit limiting.

- It's use [here in the pgbackrest secert](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/sec-pgbackrest.yaml#L19) has a few issues.
    - We should wrap this entire line in a conditional. If the user has not specified a value for `repo1-path`, then we can certainly use this line. However, if a user is attempting to take control of the backup path, then it will actually inhibit the startup process and will log errors like so: `ERROR: [031]: option 'repo1-path' cannot be set multiple times`
    - As a fallback, if the value is not set, then using the current pattern should work.
- By extension, the [service defined here](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/svc-timescaledb.yaml#L7-L13) uses the `clusterName`, which is arguably fine, but the fact that it is used here just means that we can not haphazardly adjust the value of `clusterName` in order to control the `repo1-path`. The values are coupled in a bad way right now.

Allowing `repo1-path` to be directly overwritten by a user, and wrapping its current template line in some conditional logic should address all of the above issues.

**Comment by thedodd** [comment]
I'm happy to pop a PR for this on Monday as well `:)`

**Comment by feikesteenbergen** [comment]
Sounds sane, we need to allow some more customization of the backup part in general,
see also PR #108, which needs some work still.

For example, I may wish to bootstrap a cluster from s3 bucket `a`, (say a disaster recovery test), but have it backing up to s3 bucket `b`.

The `clusterName` does have some magic to it, especially as Patroni has some tight coupling based on this value, however for the backup part we should be fine to override s3 bucket paths.
