### ISSUE TITLE
Trying to change PVC size fails

### ISSUE THREAD

**Issue by drpebcak** [timescale/timescaledb-kubernetes#120]
Trying to change `persistentVolumes.data.size` results in this error:

```
Error: UPGRADE FAILED: cannot patch "timescale-timescaledb" with kind StatefulSet: StatefulSet.apps "timescale-timescaledb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

On closer examination it looks like this is because that value tries to change the `volumeClaimTemplates` section of the statefulset.

**Comment by feikesteenbergen** [comment]
This is currently not supported for StatefulSets, so there's nothing we can do in these Helm Charts to make it work.

https://github.com/kubernetes/kubernetes/issues/68737

Note however, that you *can* resize existing `pvc`'s (ebs on aws for example), however it involves a 
few steps, for more details see:

https://www.jeffgeerling.com/blog/2019/expanding-k8s-pvs-eks-on-aws
