### ISSUE TITLE
Looking for Dockerized HA version of TimeScaleDB  

### ISSUE THREAD

**Issue by rushabh-harness** [timescale/timescaledb-kubernetes#126]
Hi,
I am trying to setup an HA dockerized version of TimeScaleDB referencing the following blog: https://blog.timescale.com/blog/high-availability-timescaledb-postgresql-patroni-a4572264a831/
I see that https://github.com/zalando/spilo is a project that comprises of Patroni + PostGreSQL which also has TimeScaleDB extension enabled as part of it
I see that this is something that the TimeScaleDB team also is probably coming up soon as per this thread: https://github.com/timescale/timescaledb-kubernetes/issues/88
My question is should I pursue the Spilo approcach to reach my solution or is the TimeScaleDB team going to release an official version of dockerized timescaledb-docker-ha soon.
Thanks

_Originally posted by @rushabh-harness in https://github.com/timescale/timescaledb-kubernetes/issues/88#issuecomment-586447463_

**Comment by feikesteenbergen** [comment]
We're working on opening up the repo; should be within weeks.

**Comment by rushabh-harness** [comment]
Thanks for the response !! Looking forward to working with it.

**Comment by feikesteenbergen** [comment]
I just opened up https://github.com/timescale/timescaledb-docker-ha.
