### ISSUE TITLE
timescaledb service end point

### ISSUE THREAD

**Issue by SiddiqueAhmad** [timescale/timescaledb-kubernetes#136]
i have tried this helm chart two three times, but it is not exposing 5432 port properly, even with default configuration, loadbalancer remain down, i am checking with digitalocean

is there way i can connect it directly ?

**Comment by feikesteenbergen** [comment]
Could you elaborate a bit? This may be an issue with Digital Ocean, these Helm Charts, or something very different.

To reproduce I did this:

```console
helm3 upgrade --install bugtest ./charts/timescaledb-single/
```

And this is what I run into with DO:

```console
kubectl describe service/bugtest
```
```text
  Warning  SyncLoadBalancerFailed  31s                service-controller  Error syncing load balancer: failed to ensure load balancer: failed to create load-balancer: POST https://api.digitalocean.com/v2/load_balancers: 429 (request "20b5a9be-d807-42b2-a772-72e926d3d61f") You have reached your load balancer limit, maximum allowed 10.
```
So, clearly I'm running into a Digital Ocean limit here.


For troubleshooting, could you provide the output of:

```console
kubectl get service/$RELEASE
```

**Comment by SiddiqueAhmad** [comment]
thanks for replying, i am attaching screenshot of nodebalancer as well as sharing output of service, timescale db is running, i have checked via port forward of pod, but not able to connect to DB remotely 


![image](https://user-images.githubusercontent.com/1517075/76955458-0fa66380-6934-11ea-9280-898a0aba4c7a.png)

![image](https://user-images.githubusercontent.com/1517075/76955510-28af1480-6934-11ea-8c37-950984d9b2a9.png)

![image](https://user-images.githubusercontent.com/1517075/76955572-3ebcd500-6934-11ea-8c99-42e63c488aac.png)

**Comment by feikesteenbergen** [comment]
Looks good, you may be running into a firewall or something similar; that's hard to establish from here.

From inside the kubernetes cluster (from another timescale pod for example) what does the following do:

```
pg_isready -h 157.230.192.232 -p 5432
pg_isready -h timescale-16 -p 5432
```

Also, to address your actual question, however it would only be a debugging/troubleshooting step IMHO:

```console
kubectl port-forward $(kubectl get pod -l cluster-name=timescale-16,role=master -o name) 15432:5432
```
In a separate console, you should be able to connect:
```console
psql -h localhost -p 15432 [...]
```

**Comment by EsajeeSolutions** [comment]
I have checked the port forwarding method and it's working, for other method I will share update

**Comment by SiddiqueAhmad** [comment]
pg_isready -h timescale-16 -p 5432 

is fine, but not with IP

**Comment by feikesteenbergen** [comment]
Ok, that means the Service is working, but you cannot connect to the public IP.
That seems like a firewall to me, I'd advise you to take that up with Digital Ocean, either their support documentation or their support channels.

**Comment by SiddiqueAhmad** [comment]
ok thanks for your time, nodebalancer always say down, I logged in server, port is listening but only ipv6

**Comment by SiddiqueAhmad** [comment]
i can access other services but connection timeout on the timescale service, and even can not connect pod direct address from other non timescale pod

**Comment by SiddiqueAhmad** [comment]
build new cluster and from this github repo, and it worked now, thanks for your time
