### ISSUE TITLE
Unable to upgrade to chart version 0.5.4 (on Helm2 client)

### ISSUE THREAD

**Issue by schahal** [timescale/timescaledb-kubernetes#137]
### Steps to reproduce

1. Have a timescale v0.5.3 on your cluster (see "Environment" below):

    ```
    $ helm list
    NAME                    	REVISION	UPDATED                 	STATUS  	CHART                       	APP VERSION	NAMESPACE
    ...
    timescale               	9       	Tue Mar 3 19:03:37 2020	DEPLOYED	timescaledb-single-0.5.3    	           	<redacted>
    ```

2. Try to upgrade to v0.5.4: 

    ```
    $ helm upgrade --install timescale  timescaledb/timescaledb-single --set  ... --version=0.5.4
    ```

    Results in:

    ```
    Error: parse error in "timescaledb-single/templates/statefulset-timescaledb.yaml": template: timescaledb-single/templates/statefulset-timescaledb.yaml:225: function "concat" not defined
    ```

### Workaround available

Stick to 0.5.3; we're unable to upgrade our helm client/server to v3 due to a deployment system that currently requires v2 (as v3 is not backwards compatible)

### Environment 

Kubernetes version 1.14.9
Helm Client/Server: 2.14.2

**Comment by feikesteenbergen** [comment]
This is not a Helm 2 vs Helm 3 issue, I can install just fine with Helm 2.16.1.

**Comment by feikesteenbergen** [comment]
I'll be closing this, with the solution being: Upgrade to Helm 2.16 or Helm 3.
