### ISSUE TITLE
Deployment Failed on Kubernetes

### ISSUE THREAD

**Issue by sarthak-k** [timescale/timescaledb-kubernetes#140]
Hi,

Thanks for Helm chart, I'm trying to deploy this on the local cluster with the following add-ons enabled for Kubernetes:
1. DNS
2. Registry
3. Dashboard

After running  microk8s helm install --name timescale-db charts/timescaledb-single --set credentials.postgres="Password --set credentials.admin="Password" --set credentials.standby="Password", after the execution I can see various services are being created. But failing to start default pod with following logs:

microk8s kubectl logs pod/timescale-db-timescaledb-0 -n default
install: cannot change owner and permissions of ‘/var/lib/postgresql/data’: No such file or directory
install: cannot change owner and permissions of ‘/var/lib/postgresql/wal/pg_wal’: No such file or directory.

Is there anything which I need to change in config?

**Comment by feikesteenbergen** [comment]
I may be guessing here, I develop mostly using microk8s and have no issues.

Have you enabled storage? https://microk8s.io/docs/addons#list

**Comment by sarthak-k** [comment]
Yes. Storage is enabled. I guess this is securityContext issue because there was a similar issue with Zookeeper in Dremio helm.

**Comment by feikesteenbergen** [comment]
Could you report back if the following issue is your issue?

https://github.com/ubuntu/microk8s/issues/516

**Comment by sarthak-k** [comment]
Hi,

I don't think so it's the issue, the issue was closed on June 2019, my installation of Microk8s is of April 2020. I had similar issue with ZooKeeper but I could resolve that with modifying the securityContext block and removing the `runAsUser: 1000` config.

**Comment by ismailyenigul** [comment]
Hi @sarthak-k 
can you send output of

```
# microk8s status
# microk8s kubectl describe  pod timescale-db-timescaledb-0
```
I just tested on ubuntu 18 with latest microk8s and helm3 and works fine.

```
microk8s helm3 install  timescale-db timescale/timescaledb-single --set credentials.postgres="Password" --set credentials.admin="Password" --set credentials.standby="Password"
```

**Comment by sarthak-k** [comment]
Hi @ismailyenigul 

I did installed timescale-db single node successfully, I was trying on for multi-node deployment.

**Comment by feikesteenbergen** [comment]
@sarthak-k could you share how you fixed the problem so that others may also benefit?

**Comment by sarthak-k** [comment]
Hi,

I guess using helm3 rather than helm is the only notable change I did, also multi-node deployment is something I couldn't install yet. Will be trying for it as I get time.

**Comment by stevetae93** [comment]
hi,

I am also suffering from the same issue. Helm3 was used, but it was the same. Can you give me a tip?

**Comment by kzay** [comment]
Same here, bug still present.
Using Helm 3 too.
