### ISSUE TITLE
 on last version not create secret

### ISSUE THREAD

**Issue by devopsrelband** [timescale/timescaledb-kubernetes#147]
In the latest version, I get an error:
MountVolume.SetUp failed for volume "certificate" : secret "timescaledb-certificate" not found

**Comment by feikesteenbergen** [comment]
There are some changes happening to the repository that will move all of the Secrets out of the Helm Chart. The error message you receive indicates that the Secret's have not yet been created in Kubernetes.

These steps are described here:

https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single#installing

If you're looking to upgrade a previous chart, or want to run a stable version, I would advise you not to use the latest tag/master branch, but a release marked production, which is [v0.5.5](https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.5.5).

A future release (0.6.0) will contain a migration guide for v0.5.x to v0.6.x releases.

**Comment by feikesteenbergen** [comment]
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#mountvolumesetup-failed-for-volume-volume-name-secret-release-secret-not-found
