### ISSUE TITLE
TimeScaleDB SingleNode helm chart 0.5.8 fails to come up

### ISSUE THREAD

**Issue by rushabh-harness** [timescale/timescaledb-kubernetes#151]
I am trying to setup a timescaledb-single helm chart 0.5.8 with 3 replicas, backup disabled. 

The first node itself fails to come up. I deleted the statefulset and the pvc and tried to bring it back up, it still fails to come up. 

My values.yaml is as follows 

```    
    replicaCount: 3

    secretnames:
      credentials: timescaledb-credentials
      certificate: timescaledb-certificate

    persistentVolumes:
      data:
        enabled: True
        storageClass: 'standard'
        size: 200Gi
      wal:
        enabled: False
        size: 20G
        storageClass: 'standard'
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
```
The node is constantly logging at an interval of 10 seconds

```
2020-05-08 07:21:07,751 ERROR: failed to bootstrap (without leader)
2020-05-08 07:21:17,750 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1
2020-05-08 07:21:17,751 ERROR: failed to bootstrap (without leader)
2020-05-08 07:21:27,751 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1
```

**Comment by feikesteenbergen** [comment]
It seems there is a remnant left of a previous(?) installation,
what does

```console
kubectl get endpoints/$NAME
```

Show you?

**Comment by feikesteenbergen** [comment]
Also 0.5.8 was marked as pre-release and removed after found wanting.
For now, I'd stay on the latest stable release as listed here:

https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.5.5

Within the not too long distance, we'll release an 0.6.x version

**Comment by feikesteenbergen** [comment]
We'll need some good documentation around it, and perhaps, if we can, print out in the logs the link to the documentation.

**Comment by rushabh-harness** [comment]
@feikesteenbergen yes, there were 2 stale endpoints lying around 

```
timescaledb-single-chart                         
timescaledb-single-chart-config
```
Deleting the 2 made it work. 

It would definitely help if there is some documentation around it. 

Regarding 0.5.8, point taken. I ll roll back the version to 0.5.5. 

Thanks for the help
