### ISSUE TITLE
Pod ‘[RELEASE]-timescaledb-0’ does not have a named port ‘postgresql’ when kubectl port-forward to custom nodePort service

### ISSUE THREAD

**Issue by fernando-almeida** [timescale/timescaledb-kubernetes#158]
The named target port does not seem to be defined.
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/svc-timescaledb.yaml#L27

**Comment by fernando-almeida** [comment]
Some additional info that may be worth analyzing for context.
This was tested on a Digital Ocean cluster with K8s version 1.17.5.
I've heard reports from antoher that was able to make this work with a K8s cluster with version 1.16.

**Comment by fernando-almeida** [comment]
See discussion in communty Slack #general [thread](https://app.slack.com/client/T4GT3N2JK/C4GT3N90X/thread/C4GT3N90X-1589661648.492100)

**Comment by feikesteenbergen** [comment]
This was just released as https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.6.1
