### ISSUE TITLE
Running generate_kustomization.sh fails on mac

### ISSUE THREAD

**Issue by estein9825** [timescale/timescaledb-kubernetes#165]
I downloaded the helm chart via the suggested command:
```
helm pull timescale/timescaledb-single --untar
```
And then attempted to run generatore_kustomization.sh on my mac.

The following errors occured:
```
sed: ./kustomize/example/kustomization.yaml: No such file or directory
tr: Illegal byte sequence
tr: Illegal byte sequence
tr: Illegal byte sequence
Generating a RSA private key
..............................................................................................................++++
............++++
```

No only is the example directory missing but macs don't like tr.  To get around the example error I had to download the example directory manually.  And to get around the tr error, I had to add this to the `generate_kustomization.sh` scriptr:
```
export LC_CTYPE=C
```

**Comment by feikesteenbergen** [comment]
This was merged before you raised the issue:

https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/generate_kustomization.sh#L9

Could you tell us which version you're using?

**Comment by feikesteenbergen** [comment]
This was already fixed, but must surely be fixed with the latest release:

https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.6.2

Can you confirm?
