### ISSUE TITLE
Upgrade disk space forbidden

### ISSUE THREAD

**Issue by throrin19** [timescale/timescaledb-kubernetes#180]
Hello,

I try to upgrade disk space directly in helm responses. I use EBS storage with 
`allowVolumeExpansion: true` in StorageClass used.

When i upgrade my deployed chart, I have this error : 

```
Failed to install app timescaledb. Error: UPGRADE FAILED: failed to replace object: StatefulSet.apps "timescaledb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**Comment by throrin19** [comment]
I think the problem is in the `statefulset-timescaledb.yaml`. The statefullset can upgrade limited number of values - `replicas`, `template`, and `updateStrategy`.

In this chart, all pvc are set directly in the statefullset part. With that, it's not possible to update the `resources.requests.storage` of specific volume (data or wal)

**Comment by feikesteenbergen** [comment]
This is a Kubernetes StatefulSet issue, there's nothing that we can do about this in these Charts:

https://github.com/kubernetes/kubernetes/issues/68737
