### ISSUE TITLE
TSDB installation fails with helm chart provided in https://github.com/timescale/timescaledb-kubernetes

### ISSUE THREAD

**Issue by ravi-mummulla** [timescale/timescaledb-kubernetes#199]
Steps to repro:
1. pull down timescaledb-single using Helm
2. Run kustomization.sh
3. Run helm upgrade using the following commandline:

helm upgrade timescaledb timescalesdb/timescaledb-single --install --namespace=monitoring --set image.tag=latest-pg12 --set global.storageClass=my_storageclass --set persistence.storageClass=my_storageclass --set useStatefulSet=false --debug
```
client.go:173: [debug] checking 11 resources for changes
client.go:431: [debug] Looks like there are no changes for ServiceAccount "timescaledb"
client.go:431: [debug] Looks like there are no changes for Secret "timescaledb-passwords"
client.go:431: [debug] Looks like there are no changes for ConfigMap "timescaledb-patroni"
client.go:431: [debug] Looks like there are no changes for ConfigMap "timescaledb-scripts"
client.go:431: [debug] Looks like there are no changes for Role "timescaledb"
client.go:431: [debug] Looks like there are no changes for RoleBinding "timescaledb"
client.go:431: [debug] Looks like there are no changes for Service "timescaledb-config"
client.go:431: [debug] Looks like there are no changes for Service "timescaledb-replica"
client.go:431: [debug] Looks like there are no changes for Service "timescaledb"
client.go:108: [debug] creating 1 resource(s)
client.go:467: [debug] Watching for changes to Job timescaledb-patroni-s2 with timeout of 5m0s
client.go:495: [debug] Add/Modify event for timescaledb-patroni-s2: ADDED
client.go:534: [debug] timescaledb-patroni-s2: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:495: [debug] Add/Modify event for timescaledb-patroni-s2: MODIFIED
client.go:534: [debug] timescaledb-patroni-s2: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:495: [debug] Add/Modify event for timescaledb-patroni-s2: MODIFIED
upgrade.go:351: [debug] warning: Upgrade "timescaledb" failed: post-upgrade hooks failed: job failed: DeadlineExceeded
Error: UPGRADE FAILED: post-upgrade hooks failed: job failed: DeadlineExceeded
helm.go:84: [debug] post-upgrade hooks failed: job failed: DeadlineExceeded
UPGRADE FAILED
main.newUpgradeCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:146
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by drpebcak** [comment]
`--set persistence.storageClass=my_storageclass` this doesn't seem valid - do you actually have a storageclass configured that is called this?

**Comment by drpebcak** [comment]
Judging by the error message, I would say the answer is no.

**Comment by ravi-mummulla** [comment]
Here's that I am setting, but it seems that it isn't being picked up. Please advise on the correct variable to set. Thank you.
        --set "persistence.enabled=true"
        --set "persistence.storageClass=my_storage_class"
        --set "persistence.accessMode=ReadWriteMany"
        --set "global.storageClass=my_storage_class"
        --set "StorageClass=my_storage_class"

~$ kubectl get pvc | grep timescale
storage-volume-timescaledb-0                     Pending
storage-volume-timescaledb-single-1597178262-0   Pending
wal-volume-timescaledb-0                         Pending
wal-volume-timescaledb-single-1597178262-0       Pending
~$ kubectl describe pvc
Name:          storage-volume-timescaledb-single-1597178262-0
Namespace:     monitoring
StorageClass:
Status:        Pending
Volume:
Labels:        app=timescaledb-single-1597178262
               cluster-name=timescaledb-single-1597178262
               heritage=Helm
               purpose=data-directory
               release=timescaledb-single-1597178262
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason         Age                     From                         Message
  ----    ------         ----                    ----                         -------
  Normal  FailedBinding  66s (x13662 over 2d8h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

**Comment by ravi-mummulla** [comment]
When I set the following variables in helm upgrade commandline, I get the following error:
--set "persistentVolumes.data.storageClass=my_storage_class"
--set "persistentVolumes.data.accessModes=ReadWriteMany"
--set "persistentVolumes.wal.storageClass=my_storage_class"
--set "persistentVolumes.wal.accessModes=ReadWriteMany"

Error: YAML parse error on timescaledb-single/templates/statefulset-timescaledb.yaml: error converting YAML to JSON: yaml: line 259: could not find expected ':'
helm.go:84: [debug] error converting YAML to JSON: yaml: line 259: could not find expected ':'
YAML parse error on timescaledb-single/templates/statefulset-timescaledb.yaml

**Comment by feikesteenbergen** [comment]
Please look at issue https://github.com/timescale/timescaledb-kubernetes/issues/204 for the syntax error.

**Comment by feikesteenbergen** [comment]
What storageclasses do you have:
```
kubectl get storageclass
```

What does your storage provider of your kubernetes cluster say about the PVC's?
Also have a look at [stackoverflow](https://stackoverflow.com/questions/44891319/kubernetes-persistent-volume-claim-indefinitely-in-pending-state) for troubleshooting this one

**Comment by feikesteenbergen** [comment]
Also, `persistence.storageClass` is not an actual value you can set, 
look at the [Administration Guide](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#configuration) for a list of allowed values.

**Comment by ravi-mummulla** [comment]
I am using the storage class that has been provisioned earlier. This storage class is shared across various pods.

$ kubectl get storageClass
NAME                 PROVISIONER          AGE
my_storageclass   my_storageclass   104d

Here are the details of my PVC:

kubectl get pvc/storage-volume-timescaledb-0 -o yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2020-08-14T08:06:32Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: timescaledb
    cluster-name: timescaledb
    heritage: Helm
    purpose: data-directory
    release: timescaledb
  name: storage-volume-timescaledb-0
  namespace: monitoring
  resourceVersion: "86637442"
  selfLink: /api/v1/namespaces/monitoring/persistentvolumeclaims/storage-volume-timescaledb-0
  uid: 58199d3b-4dae-423f-bbad-44d557aa47d3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
status:
  phase: Pending

**Comment by ravi-mummulla** [comment]
A quick update. When persistent volumes are disabled for data and wal storage (persistentVolumes.wal.enabled=false and persistentVolumes.data.enabled=false), the pod deploys successfully. When persistence is specified (persistentVolumes.data.storageClass=my_storage and persistentVolumes.data.accessModes={ReadWriteMany}), the pod ends up in the pending state with the following message:
----
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  46s (x4 over 3m26s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
----

**Comment by drpebcak** [comment]
This would indicate there is a problem with the storageclass you've configured - it isn't creating the volumes.

**Comment by ravi-mummulla** [comment]
This storage class is used by other sevices in our k8s deployment. Do I need to explicitly create volumes in this storage class?

**Comment by ravi-mummulla** [comment]
I was able to get this working with the following settings:
        --set persistentVolumes.data.storageClass=my_storage
        --set persistentVolumes.data.accessModes={ReadWriteOnce}
        --set persistentVolumes.wal.enabled=false
