### ISSUE TITLE
Override y/n prompts when using generate_kustomization.sh & installing secrets in automated helm installs

### ISSUE THREAD

**Issue by ravi-mummulla** [timescale/timescaledb-kubernetes#205]
I have the following code before I issue helm upgrade --install command:

helm pull timescalesdb/timescaledb-single --untar --untardir ./timescaledb/
bash ./timescaledb/timescaledb-single/generate_kustomization.sh ${TIMESCALEDB_RELEASE}
# bash kubectl kustomize ./
# kubectl apply -k "./timescaledb/timescaledb-single/kustomize/timescaledb"

It isn't clear how to override the following prompts from generate_kustomization.sh:
----
Do you want to configure the backup of your database to S3 (compatible) storage? (y/n)
----

----
You may now wish to (p)review the files that have been created and further edit
them before deployment.

To preview the deployment of the secrets:

    kubectl kustomize "./timescaledb/timescaledb-single/kustomize/timescaledb"

Or you may want to install the secrets directly? (y/n)

To install these secrets, execute:
    kubectl apply -k "./timescaledb/timescaledb-single/kustomize/timescaledb"
----

**Comment by ravi-mummulla** [comment]
It looks like these are the variables to set in my helm deployment script, but they don't take effect when I set them: SKIP_PGBACKREST_CONFIG and SKIP_INSTALL:

SKIP_PGBACKREST_CONFIG=""
SKIP_INSTALL=""

**Comment by feikesteenbergen** [comment]
You could do:

```console
yes | generate_kustomization.sh $RELEASE
```
that will answer `y` to every question asked.

Although it may be good to have a way to automatically install the secrets as well

**Comment by feikesteenbergen** [comment]
Could you provide the full call to the script here?

**Comment by ravi-mummulla** [comment]
Thanks for your input. Please advice if this is the right way to generate and install the secrets. Here's the full script:

#!/usr/bin/env bash

# Common utilities, variables and checks for all build scripts.
source "${ARCH_APP_ROOT}/src/artifacts/shellutils/init.sh"
SKIP_PGBACKREST_CONFIG=""
SKIP_INSTALL=""

common::load_env_vars

# helm search repo timescale
# https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single
TIMESCALEDB_RELEASE="timescaledb"
TIMESCALEDB_CHART="timescalesdb/timescaledb-single"
TIMESCALEDB_IMAGE_TAG="latest-pg12"

function kubernetes::deploy_timescaledb() {
    local -r ns=$1

    helm_opts=(
        --install
        --namespace=${ns}
        --set image.tag=${TIMESCALEDB_IMAGE_TAG}
        --set persistentVolumes.data.storageClass=disk.csi.azure.com
        --set persistentVolumes.data.accessModes={ReadWriteMany}
        --set persistentVolumes.wal.storageClass=disk.csi.azure.com
        --set persistentVolumes.wal.accessModes={ReadWriteMany}
        --debug
    )

    if [ -d ${ARCH_APP_ROOT}/timescaledb/ ]; then rm -Rf ${ARCH_APP_ROOT}/timescaledb/; fi
    helm pull timescalesdb/timescaledb-single --untar --untardir ${ARCH_APP_ROOT}/timescaledb/
    chmod a+x ${ARCH_APP_ROOT}/timescaledb/timescaledb-single/generate_kustomization.sh
    SKIP_PGBACKREST_CONFIG=""
    SKIP_INSTALL=""
    ${ARCH_APP_ROOT}/timescaledb/timescaledb-single/generate_kustomization.sh ${TIMESCALEDB_RELEASE}
    bash kubectl kustomize ${ARCH_APP_ROOT}/
    # kubectl apply -k "${ARCH_APP_ROOT}/timescaledb/timescaledb-single/kustomize/timescaledb"

    helm::upgrade ${TIMESCALEDB_RELEASE} ${TIMESCALEDB_CHART} "${helm_opts[@]}"
}

**Comment by ravi-mummulla** [comment]
There are two questions in generate_kustomization.sh (the first answer is N and the second answer is Y):
----
1. Do you want to configure the backup of your database to S3 (compatible) storage? (y/n)
2. The following:
To preview the deployment of the secrets:
 kubectl kustomize "./timescaledb/timescaledb-single/kustomize/timescaledb"
Or you may want to install the secrets directly? (y/n)
----
Appreciate any help clarifying on how best to do this. Setting the following env vars doesn't do the trick:
SKIP_PGBACKREST_CONFIG=""
SKIP_INSTALL=""

**Comment by ravi-mummulla** [comment]
This has fixed the issue:
export SKIP_PGBACKREST_CONFIG=Y
export SKIP_INSTALL=Y
