### ISSUE TITLE
Installing s3fs to test storage tiering to S3

### ISSUE THREAD

**Issue by nethsix** [timescale/timescaledb-kubernetes#207]
**Describe the bug**
This is not a bug but rather request for help to get `sudo` working in order to test S3 storage tiering, and add the feature into this helm if that is deemed something good.

I'm trying to install s3fs (https://cloud.netapp.com/blog/amazon-s3-as-a-file-system) so that I can mount S3 as a directory and create a timescaledb tablespace on that directory to store older chunks.

I apologize in advance if I missed something obvious, or this is not the right place to get help on this.

**To Reproduce**
```
$ kubectl exec -it <release-name>-timescaledb-0

$ sudo apt-get install s3fs
sudo command not found
```
**Expected behavior**
Perhaps sudo exist and will work?

**Deployment**
- What is in your `values.yaml`
Default
- What version of the Chart are you using?
timescaledb-single, version: 0.5.5

- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s)
EKS

**Comment by feikesteenbergen** [comment]
One of the fundamental design decisions for this setup is that these containers do *not* run as [privileged containers](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privileged).

That means that `sudo`, or doing anything that would require `root` inside the container is a no go.

I don't know much about s3fs, however some [googling shows](https://github.com/informatics-lab/s3-fuse-flex-volume) that you may be able to create s3fs volumes on the hosting nodes.

**MAJOR WARNING**: I don't think storing PostgreSQL data files in an S3 bucket is wise. I expect major issues, both in latency as well in constency of your data files.

I don't think S3 offers POSIX semantics, however that is the minimum bar required for PostgreSQL

> any file system with POSIX semantics can be used for PostgreSQL
https://www.postgresql.org/docs/current/creating-cluster.html#CREATING-CLUSTER-FILESYSTEM

You could also explore native integrations with s3, using an s3 [foreign data wrapper](https://wiki.postgresql.org/wiki/Foreign_data_wrappers) for example: https://pgxn.org/dist/s3_fdw/doc/s3_fdw.html

However, that fdw is not part of the default Docker Image, so you'll have to build your own.

**Comment by nethsix** [comment]
Thank your for your advice!
