### ISSUE TITLE
How to upgrade from pg11 to pg12 with this chart ?

### ISSUE THREAD

**Issue by throrin19** [timescale/timescaledb-kubernetes#213]
Hello,

I've seen the last version migrate postgres from version 11 to version 12. It's possible to force the version to 11 but, how I can use the `pg_upgrade` command with the single nodes helm chart ?

It's possible to have an example ?

Thanks

**Comment by feikesteenbergen** [comment]
There is no `pg_upgrade` support for these Helm Charts (yet, if ever).

If you need to migrate your data, you can create a new deployment and use [`pg_dump`](https://www.postgresql.org/docs/12/app-pgdump.html) (or `pg_dumpall`).

> Doing a pg_upgrade is (for now) out of scope for these Helm Charts.
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/upgrade-guide.md#upgrading-from-06-to-07
