### ISSUE TITLE
Modify PGBouncer file permissions to permit viewing by authorized accounts

### ISSUE THREAD

**Issue by pgodfrin** [timescale/timescaledb-kubernetes#220]
**Describe the bug**
After deploying PGBouncer, the userlist.txt and pgbouncer.ini files are set to 640:

> -rw-r----- 1 root root    0 Apr 28 07:28 userlist.txt
> -rw-r----- 1 root root 9.2K Apr 28 07:28 pgbouncer.ini

**To Reproduce**
Default result of chart

**Expected behavior**
File permissions to be set to 644 to permit viewing. Perhaps the userlist.txt should remain 640 for security.

**Deployment**
timescaledev/timescaledb-ha:pg12.4-ts1.7.2-latest

**Comment by feikesteenbergen** [comment]
These lists are not used in the default pgBouncer configuration - the pgBouncer is a pass-through configuration,
verifying users/databases against the actual database.

What is the issue/error message you're running into?

**Comment by drpebcak** [comment]
Is this using #222? Does pgbouncer not work with the userlist.txt? In my deployment (which isn't using #222 yet), ownership is `root:postgres`, not `root:root`

**Comment by pgodfrin** [comment]
In my install it looks like this:
-rw-r----- 1 root root 0 Apr 28 07:28 userlist.txt
-rw-r----- 1 root root 9.2K Apr 28 07:28 pgbouncer.ini

To Feike, the pgbouncer.ini contains config info, per the docs:
Description
Generic settings
Log settings
Console access control
Connection sanity checks, timeouts
TLS settings
Dangerous timeouts
Low-level network settings
Section [databases]
Section [users]
Include directive
Authentication file format
HBA file format
Example

Not being able to see the config makes troubleshooting impossible.

**Comment by feikesteenbergen** [comment]
`pgbouncer` is using the configuration file that is generated here:

https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/configmap-pgbouncer.yaml#L24

It is *not* using `pgbouncer.ini`, it using the one from the configmap:

This is the startup command for the pgbouncer container:
```yaml
        command:
        - /usr/bin/env
        - -i
        - /usr/sbin/pgbouncer
        - /etc/pgbouncer/pgbouncer-sidecar.ini
```

Also, it is *not* using `userlist.txt`, however if we merge #222, it may, and then it will be visible.

To troubleshoot currently, you could do:

`kubectl get configmap ${RELEASE}-pgbouncer -o 'go-template={{index .data "pgbouncer-sidecar.ini"}}'`

Alternatively, you can have a look inside the sidecar container:

`kubectl exec -ti pod/${RELEASE}-0 -c pgbouncer -- cat /etc/pgbouncer/pgbouncer-sidecar.ini`

**Comment by pgodfrin** [comment]
OK, Thanks very much Feike, I didn't know that. I think merging #222 is not a bad idea, just to be able to permit admins who don't have visibility to the charts.
Insofar as this issue, I'll close it as your answer is satisfactory and much appreciated,
