### ISSUE TITLE
Writes not scaling

### ISSUE THREAD

**Issue by hyprnick** [timescale/timescaledb-kubernetes#227]
I installed a multi-node cluster following the directions here https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-multinode.  This created a single access pod with 3 data pods. I didn't modify any defaults.  

I then started the benchmark: https://github.com/timescale/tsbs using the following arguments: 

`./gen --format timescaledb --use-case iot --seed 123 --scale 4000 | ./load --postgres=\"sslmode=disable\" --host=\"timescale-timescaledb.default.svc.cluster.local\" --port=5432 --user=bench --pass=XX --batch-size 10 --workers W`

I used a Kubernetes job to avoid any latency issues.  I ran multiple tests using different values for the workers setting. 

workers | rows/s
---|---
1 | 1200
2 | 2100
3 | 2400
4 | 2500
5 | 2900

Inspecting the resource usage, I'm seeing the following:  
```
timescale-timescaledb-access-0    162m         394Mi
timescale-timescaledb-data-0      1m           65Mi
timescale-timescaledb-data-1      1m           64Mi
timescale-timescaledb-data-2      1m           65Mi
```

Only the access node is receiving all the writes. The data nodes don't seem to be getting anything.  Is there a configuration setting I'm missing?  

Thank you!

**Comment by feikesteenbergen** [comment]
The default of the multinode is that tables are created on the node where the query is executed.

You could have a look here, specifically at [`create_distributed_hypertable'](https://docs.timescale.com/beta-v2.0.0/api#create_distributed_hypertable`) for details on how to create a distributed hypertable.
