### ISSUE TITLE
[ISSUE] Multinode does not start with non-root user

### ISSUE THREAD

**Issue by bkief** [timescale/timescaledb-kubernetes#249]
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**
Multinode does not start with non-root User

**To Reproduce**
Add `runAsUser: 1000` to the statefulset security context

**Expected behavior**
The pod should successfully start

**Deployment**
- What is in your `values.yaml` - Default
- What version of the Chart are you using? - Latest
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s) - Docker k8s & private k8s cloud

**Logs**
When running with uid 1000:
```
kubectl logs timescale2-timescaledb-access-0 -c initdb
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/pgdata ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2021-01-03 03:46:54.137 UTC [71] FATAL:  data directory "/var/lib/postgresql/pgdata" has wrong ownership
2021-01-03 03:46:54.137 UTC [71] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/pgdata"
running bootstrap script ...
```

**Additional context**
Many production K8S clusters do not allow containers to run as root for security reasons. All modern deployments should run as a non-root user for best security practices. This is not currently possible for the current multi-node chart.

**Comment by feikesteenbergen** [comment]
The design of this Helm Chart always assumed these containers to *not* run as root, but as a regular user.
It is actually expected to fail if run as root, as PostgreSQL will reject to start initdb as root.

> The files belonging to this database system will be owned by user "postgres".
Judging by these logs, the container is started with the user `postgres`.

If I change the following in our Charts:

```diff
diff --git charts/timescaledb-multinode/templates/statefulset-timescaledb-accessnode.yaml charts/timescaledb-multinode/templates/statefulset-timescaledb-accessnode.yaml
index f6190e5..a42600a 100644
--- charts/timescaledb-multinode/templates/statefulset-timescaledb-accessnode.yaml
+++ charts/timescaledb-multinode/templates/statefulset-timescaledb-accessnode.yaml
@@ -31,6 +31,7 @@ spec:
         # The postgres user inside the TimescaleDB image has uid=1000.
         # This configuration ensures the permissions of the mounts are suitable
         fsGroup: 1000
+        runAsUser: 1000
       initContainers:
       - name: initdb
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
diff --git charts/timescaledb-multinode/templates/statefulset-timescaledb-datanode.yaml charts/timescaledb-multinode/templates/statefulset-timescaledb-datanode.yaml
index e4ec997..5aea44c 100644
--- charts/timescaledb-multinode/templates/statefulset-timescaledb-datanode.yaml
+++ charts/timescaledb-multinode/templates/statefulset-timescaledb-datanode.yaml
@@ -31,6 +31,7 @@ spec:
         # The postgres user inside the TimescaleDB image has uid=1000.
         # This configuration ensures the permissions of the mounts are suitable
         fsGroup: 1000
+        runAsUser: 1000
       initContainers:
       - name: initdb
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

Everything works fine, so I cannot readily reproduce this issue.


What could however cause this, is that the Physical Volume backing the PVC was already used and is owned by a `uid` that is not 1000. The easiest way to figure out if it might be a stale PVC, is to create the deployment under a different name, or in a new k8s namespace.

**Comment by bkief** [comment]
@feikesteenbergen Thanks for taking a look at this. This was in a fresh namespace, so I don't believe there was a stake PVC. I did get it to work locally on Minikube with K8S 1.20. The version I was trying to deploy to was 1.17. I will try again in the coming days to make double-sure.  I suspect something was going awry in the init scripts. Is there any particular location you would recommend to add a `stat` to help log and debug where the ownership is getting mixed up?

**Comment by feikesteenbergen** [comment]
@bkief, if you want an interactive debug session, I would set the following in `values.yaml`:

```yaml
debug:
  # This setting is mainly for during development, debugging or troubleshooting.
  # This command will be executed *before* the main container starts. In the
  # example below, we can mimick a slow restore by sleeping for 5 minutes before starting
  execStartPre: sleep 300
```

And do some interactive troubleshooting in the pod, for example:

```shell
kubectl exec -ti pod/$name-timescaledb-0 -c timescaledb -- bash
```
```shell
ls -ld $PGDATA
ls -ld /var/lib/postgresql/pgdata
# once satisfied, let the regular process commence:
pgrep -f sleep | xargs kill
```
