### ISSUE TITLE
[ISSUE] Default values causes chart to fail to start up due to standby user

### ISSUE THREAD

**Issue by NickLavrov** [timescale/timescaledb-kubernetes#281]
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**

I have secrets for timescaledb-release-certificate and timescaledb-release-credentials defined. The credentials secret is like

```
kubectl get secret timescaledb-release-credentials -o yaml
apiVersion: v1
data:
  PATRONI_ADMIN_PASSWORD: <base64encoded>
  PATRONI_REPLICATION_PASSWORD: <base64encoded>
  PATRONI_SUPERUSER_PASSWORD: <base64encoded>
```

When I apply the chart without specifying any values.yaml, the logs in the pod say

```
2021-04-08 05:41:46 UTC [99]: [606e979a.63-1] [unknown]@[unknown],app=[unknown] [00000] LOG:  connection received: host=10.9.45.111 port=60824
2021-04-08 05:41:46 UTC [99]: [606e979a.63-2] standby@[unknown],app=[unknown] [28P01] FATAL:  password authentication failed for user "standby"
2021-04-08 05:41:46 UTC [99]: [606e979a.63-3] standby@[unknown],app=[unknown] [28P01] DETAIL:  Password does not match for user "standby".
	Connection matched pg_hba.conf line 8: "hostssl   replication     standby            all                md5"
```

**To Reproduce**
Use helm chart for the single db for version 0.8.2. Create the 2 secrets above. Deploy the chart without specifiying any other values.

**Expected behavior**
It should start up.

**Deployment**
- What is in your `values.yaml`
- Nothing
- What version of the Chart are you using?
- 0.8.2
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s)
- EKS

**Comment by peedrr** [comment]
Hi @NickLavrov. I've got the same issue. Did you resolve it?
