### ISSUE TITLE
Timescaledb 2.2 and 2.3 updates

### ISSUE THREAD

**Issue by throrin19** [timescale/timescaledb-kubernetes#292]
Hello, It's possible to have Timescaledb 2.2 and/or 2.3 versions for pg12 and 13 ?

I saw the docker repository used [timescaledev/timescaledb-ha](https://hub.docker.com/r/timescaledev/timescaledb-ha) have not yet this versions.

**Comment by steven-sheehy** [comment]
They're already available, it's just been moved to another [repository](https://hub.docker.com/r/timescale/timescaledb-ha/tags?page=1&ordering=last_updated).

**Comment by throrin19** [comment]
Thanks for this information. I can't see that anywhere.
