### ISSUE TITLE
Not rejecting issue with synchronous_mode_strict=true when only master is alive

### ISSUE THREAD

**Issue by Terence2000** [timescale/timescaledb-kubernetes#303]
The Patroni doc mentions following:
"it is absolutely necessary to guarantee that each write is stored durably on at least two nodes, enable synchronous_mode_strict in addition to the synchronous_mode. This parameter prevents Patroni from switching off the synchronous replication on the primary when no synchronous standby candidates are available. "
" As a downside, the primary is not be available for writes (unless the Postgres transaction explicitly turns of synchronous_mode), blocking all client write requests until at least one synchronous replica comes up."

But according to my test, with following configuration for this 3 nodes timescale cluster,
postgres config：synchronous_commit=remote_apply, standby_names=ANY 1
Patroni config: synchronous_mode=true, synchronous_mode_strict=true
When 2 replicas goes down and I try to insert data to master, I can still fire query to the master, but without any rejection. The insert SQL will be hanging there until I bring up one of the replicas and then the data will be inserted successfully.

Is this as expected? I'm confused because the Patroni Doc I'm reading tells me the primary will "not be available for writes", to me, I'm expecting it will reject my query, not hang there and wait and then response the result.
The observed behavior of "Not rejecting directly but taking the query, hanging there until a replica comes online and then return" is a headache, because from backend service layer software perspective, I cannot easily deal with the "no response" SQL query, should I wait it forever until a response comes back? What if the 2 replicas go down for 10 days or a month and then comes back?

**Comment by feikesteenbergen** [comment]
I think this behavior is as expected; the query is accepted as such, but your `commit` will never return until a `sync` replica is created. 

That said however, if you think this is a Patroni bug, I suggest you report it at the patroni project:

https://github.com/zalando/patroni
