### ISSUE TITLE
[ISSUE] Rogue service left after running `helm delete`

### ISSUE THREAD

**Issue by rbren** [timescale/timescaledb-kubernetes#357]
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**

I install the `single` helm chart, then delete it. It seems to replace the `timescale-config` service with a new one, which is very different from the original one installed.

This prevents doing another installation, because Helm no longer recognizes the `timescale-config` (it doesn't have the proper annotations)

**To Reproduce**
Steps to reproduce the behavior, including `helm install` or `helm upgrade` commands

```bash
❯ helm upgrade --install timescale timescaledb/timescaledb-single --create-namespace -n rbren
Release "timescale" does not exist. Installing it now.
NAME: timescale
LAST DEPLOYED: Fri Apr 22 16:56:38 2022
NAMESPACE: rbren
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
TimescaleDB can be accessed via port 5432 on the following DNS name from within your cluster:
timescale.rbren.svc.cluster.local

To get your password for superuser run:

    # superuser password
    PGPASSWORD_POSTGRES=$(kubectl get secret --namespace rbren timescale-credentials -o jsonpath="{.data.PATRONI_SUPERUSER_PASSWORD}" | base64 --decode)

    # admin password
    PGPASSWORD_ADMIN=$(kubectl get secret --namespace rbren timescale-credentials -o jsonpath="{.data.PATRONI_admin_PASSWORD}" | base64 --decode)

To connect to your database, chose one of these options:

1. Run a postgres pod and connect using the psql cli:
    # login as superuser
    kubectl run -i --tty --rm psql --image=postgres \
      --env "PGPASSWORD=$PGPASSWORD_POSTGRES" \
      --command -- psql -U postgres \
      -h timescale.rbren.svc.cluster.local postgres

    # login as admin
    kubectl run -i --tty --rm psql --image=postgres \
      --env "PGPASSWORD=$PGPASSWORD_ADMIN" \
      --command -- psql -U admin \
      -h timescale.rbren.svc.cluster.local postgres

2. Directly execute a psql session on the master node

   MASTERPOD="$(kubectl get pod -o name --namespace rbren -l release=timescale,role=master)"
   kubectl exec -i --tty --namespace rbren ${MASTERPOD} -- psql -U postgres
@rbren-2 kind-kind (rbren) ~/git/charts master ✨

✦ ❯ k get svc
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
timescale           LoadBalancer   10.96.129.145   <pending>     5432:31763/TCP   5s
timescale-config    ClusterIP      None            <none>        8008/TCP         5s
timescale-replica   ClusterIP      10.96.73.24     <none>        5432/TCP         5s
@rbren-2 kind-kind (rbren) ~/git/charts master ✨

❯ helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
timescale       rbren           1               2022-04-22 16:56:38.641603987 +0000 UTC deployed        timescaledb-single-0.11.0
@rbren-2 kind-kind (rbren) ~/git/charts master ✨

❯ helm delete timescale
release "timescale" uninstalled
@rbren-2 kind-kind (rbren) ~/git/charts master ✨

❯ k get svc
NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
timescale-config   ClusterIP   None         <none>        <none>    2s
```

**Expected behavior**

**Deployment**
- What is in your `values.yaml`
- What version of the Chart are you using?
- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s)

**Deployment**
Please share some details of what is in your Kubernetes environment, for example:

```
kubectl get all,secret,configmap,endpoints,pvc -L role -l release=$RELEASE
```

**Logs**
Please provide some details from the logs, see  [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting)

**Additional context**

**Comment by rbren** [comment]
This seems to be fixed by adding
```
metadata:
  annotations:
    "helm.sh/hook-weight": "100"
```
to templates/svc-timescaledb-config.yaml

CC @ivanfetch-fw @jdesouza

**Comment by feikesteenbergen** [comment]
This is by design, to ensure a previously initiated Database will not be reinitiated using `initdb`, but will be restored from backup if backups are available.

The [Admin Guide describes how to do a full cleanup](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#cleanup)

**Comment by rbren** [comment]
Thanks for the reply!

Unfortunately this makes it _really_ hard to use timescale as a subchart, because the cleanup instructions need to get inherited by any chart that includes timescale as a dependency (and in my experience database charts are often used as subcharts). I'd also argue it goes against the spirit of using Helm.

Would you consider making this behavior optional?
