### ISSUE TITLE
[ISSUE] replicaCount in configuration is not working 

### ISSUE THREAD

**Issue by iliyas-patel-git** [timescale/timescaledb-kubernetes#381]
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**
replicaCount is not working, tried multiple values, but it always creates by default 3 replicate pods.

**To Reproduce**
helm install mnode timescaledb/timescaledb-multinode --set replicaCount=5 --set image.tag=pg12.5-ts2.0.0-p0 --set image.repository=timescaledev/timescaledb-ha

**Expected behavior**
It should create 5 replicated pods

**Deployment**
- replicaCount=5 in helm install command
- pg12.5-ts2.0.0-p0
- minikube

**Deployment**
Linux Kubernetes

```
helm install mnode timescaledb/timescaledb-multinode --set replicaCount=5 --set image.tag=pg12.5-ts2.0.0-p0 --set image.repository=timescaledev/timescaledb-ha
kubectl get pods
```

**Logs**
Please provide some details from the logs, see  [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting)

**Additional context**

**Comment by erhhung** [comment]
You're deploying the **multinode** configuration, where `replicaCount` isn't a defined setting in the values file. You need to use `dataNodes` instead. See the first line in https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-multinode/values.yaml. As for the access node, that's always a single pod, so you'll have in total `dataNodes` + 1 pods.

**Comment by iliyas-patel-git** [comment]
Thank you erhhung.
