### ISSUE TITLE
timescaledb-single: race-condition in uninstall sometimes leading to deadlock

### ISSUE THREAD

**Issue by onprem** [timescale/timescaledb-kubernetes#397]
**Describe the bug**

The helm chart creates a service called `[<release-name>-config](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/svc-timescaledb-config.yaml)` which otherwise is created by Patroni. During uninstall, if this service gets deleted first and Patroni is still running, the service gets created again by Patroni. This is mostly harmless but if you are using the wait flag (`helm uninstall --wait`) and this happens, the uninstall command will keep waiting for the service to get deleted but that'll never happen causing a deadlock. The uninstall will eventually fail upon hitting the timeout.

**To Reproduce**
Since it's a race, it's pretty hard to reproduce with just the timescaledb-single helm chart as everything gets deleted at almost same time. But you can reproduce it fairly commonly with [tobs](https://github.com/timescale/tobs).

```bash
helm repo add timescale https://charts.timescale.com/
helm repo update
helm install --wait --timeout 600s --debug test timescale/tobs
helm uninstall --wait --timeout 600s --debug test
```

The uninstall will get stuck while waiting for all resources to get deleted.

**Expected behavior**

The service should get deleted consistently with `helm uninstall --wait` and the deadlock shouldn't happen.

**Deployment**
- The default `tobs` values were used.
- The K8s environment was `kind`

**Comment by paulfantom** [comment]
Fixed with https://github.com/timescale/timescaledb-kubernetes/pull/398
