### ISSUE TITLE
Remove the need for plaintext PostgreSQL credentials

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/timescaledb-kubernetes#70]
Currently, in `values.yaml`, the credentials for the PostgreSQL users are specified as follows:

```yaml
credentials:
  admin: cola
  # the postgres and standby users are vital for Patroni, and therefore should not be
  # removed altogether.
  postgres: tea
  standby: pinacolada
```

The password for `postgres` is not strictly needed - Patroni connects using a socket locally and uses the `standby` user remotely.
pgBackrest also connects locally through the socket, which again does not require a password.

The `standby` user does need a way to authenticate over the network - we might be able to use certificates here instead of passwords.

There is no easy solution for the `admin` user: Somehow an application will need to connect with a secret. 

Some possibilities:
## Inform users that providing a hash also works
This does not seem very user friendly, but this does already actually work, and would remove
the strict need of a literal password in the `values.yaml`:

```yaml
credentials:
  admin: SCRAM-SHA-256$4096:PXzHoUaqasigcbsBiXi5MQ==$Eguayat8bXgwC19CvH1dAlsmh2Mkj2C7wtOOLsISkEI=:YtyaUsh7sYrdYZlcHVB/HUlIzg/du67PFiOILfcrf1c=
```

## Remove `postgres` password altogether
The major downside of this approach is that some extensions require `superuser` privileges to be created/updated etc.
That mostly can be mitigated by configuring [pgextwlist](https://github.com/dimitri/pgextwlist).

## Allow `standby` to authenticate using an SSL certificate.
As all pods of the StatefulSet use the same Secret as their TLS certificate this sounds easy, however we need to take care of the case where the certificate changes, for example:

- Cert A is issued to the StatefulSet.
- Every PostgreSQL server will allow `standby` to connect using certificate A
- Cert A is replaced with Cert B
    - If a replica pod is rescheduled, it cannot connect to the primary, as it only accepts A
    - If a master pod is rescheduled, a replica will become master, which only accepts A

Possible solution: Keep a list of certificates that are allowed, not only the last one.

**Comment by agronholm** [comment]
The solution we use: [helm-secrets](https://github.com/futuresimple/helm-secrets).

**Comment by feikesteenbergen** [comment]
This has been mostly addressed and released with https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.6.1

The only thing we may wish to reconsider is to use certificates for the internode replication connections at some point, removing the need for even a standby user credential.
