### ISSUE TITLE
How to install postgis?

### ISSUE THREAD

**Issue by lonelyleaf** [timescale/timescaledb-kubernetes#80]
I try to use apt in my custom Dockerfile to install postgis but get error

```
could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory

```

Can you provide your sourec of Dockerfile,or tell something about how to install postgresql extensions?

The Dockerfile:
```
FROM timescaledev/timescaledb-ha:pg11-ts1.5

USER root
RUN apt update \
    && apt install -y postgis=2.5.1+dfsg-1 \
    && rm -rf /var/lib/apt/lists/*
USER postgres
```

**Comment by lonelyleaf** [comment]
well I managed to install postgis from source like below, but I still hope to have offical image 😀

```
FROM timescaledev/timescaledb-ha:pg11-ts1.5

USER root

ADD postgis-2.5.3.tar.gz /tmp

WORKDIR /tmp/postgis-2.5.3

#speed up in china
RUN sed -i "s@http://deb.debian.org@http://mirrors.163.com@g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
        postgresql-server-dev-11 \
        libpq-dev \
        perl \
        file \
        libgeos-dev \
        libxml2-dev \
        libgdal-dev \
        libproj-dev \
        libprotobuf-c-dev \
        libjson-c-dev \
        gcc g++ \
        libjson-c-dev \
        make \
    && ./configure \
    && make -s \
    && make -s install \
    && rm -rf /var/lib/apt/lists/*
USER postgres
```

**Comment by feikesteenbergen** [comment]
Thanks for the report! I think we'll provide a lean image (the one referenced) and a bigger image, containing postgis for example.

**Comment by feikesteenbergen** [comment]
Could you try a Docker image I created to develop this?
I created a Docker image with the addition of postgis, here is a snippet of my `values.yaml`:

```yaml
image:
  repository: timescaledev/timescaledb-ha
  tag: pg11-ts1.5-postgis
  pullPolicy: IfNotPresent
```

I included both postgis 2.5 and 3, so to install 2.5.3 (as in your example) you will need to be explicit, but for me this works:

```console
postgres=# create extension postgis version "2.5.3";
CREATE EXTENSION
postgres=# SELECT postgis_full_version();
                                                                                                    postgis_full_version                                                                                             
       
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------
 POSTGIS="2.5.3 r17699" [EXTENSION] PGSQL="110" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" GDAL="GDAL 2.4.0, released 2018/12/14" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" 
RASTER
(1 row)
```

**Comment by lonelyleaf** [comment]
@feikesteenbergen  I have  tested ` timescaledev/timescaledb-ha:pg11-ts1.5-postgis` in my single table test, seems to work fine.

**Comment by feikesteenbergen** [comment]
As of the next scheduled release of TimescaleDB I intend to have a PostGis Docker image available.

Would require some documentation updates to help you out, but after that I think this issue is addressed.

**Comment by laurids-reichardt** [comment]
Would love to see this as well!

**Comment by feikesteenbergen** [comment]
The Docker image is now going to be built regularly, including postgis. Still need to update the documentation, for now, if you use the following docker image with 1.5.1 of the Helm Charts you should be good:

`timescaledev/timescaledb-ha:pg11-ts1.6-postgis`

@laurids-reichardt @lonelyleaf

**Comment by feikesteenbergen** [comment]
For now we decided to include PostGIS in all the `timescaledb-docker-ha` images, to reduce the number of variants we have to build.

New images are being built and after a smoke test I expect them to be available within < 24 hours.
They include PostgreSQL 11.7 as well.
