### ISSUE TITLE
Unable to add helm repo

### ISSUE THREAD

**Issue by rleiwang** [timescale/timescaledb-kubernetes#85]
I've got following error when I try to add repo.   Helm client is v3.

```
 helm repo add timescalesdb 'https://github.com/timescale/timescaledb-kubernetes'                                                                                       master
Error: looks like "https://github.com/timescale/timescaledb-kubernetes" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/timescale/timescaledb-kubernetes/index.yaml : 404 Not Found
```

**Comment by feikesteenbergen** [comment]
Thanks for the report, we currently do not have a Helm index, but it certainly makes sense to add one.

**Comment by feikesteenbergen** [comment]
This is now merged, @rleiwang could you tell us whether or not these instructions:

https://github.com/timescale/timescaledb-kubernetes#repository

Are working for you now?

**Comment by rleiwang** [comment]
@feikesteenbergen Thanks for the update. It is working now.

https://github.com/bytewedge/bytewedge/blob/master/charts/bytewedge/Chart.yaml#L26
