### ISSUE TITLE
container crashes in single node deployment 

### ISSUE THREAD

**Issue by rleiwang** [timescale/timescaledb-kubernetes#86]
postgresql container enters crash loop after helm install with following error.

```
install: cannot change owner and permissions of ‘/var/lib/postgresql/wal/pg_wal’: Operation not permitted
```

**Comment by rleiwang** [comment]
helm delete didn't remove PVC. It worked after cleanup. Then, I ran into the following error.

```
error: cannot attach to *v1.Service: invalid service 'mytest': Service is defined without a selector
```

**Comment by feikesteenbergen** [comment]
Helm does not remove `pvc's`, that is part of Helm:

https://github.com/helm/helm/issues/5156

We ran into this ourselves, so we documented this here:
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#cleanup

**Comment by feikesteenbergen** [comment]
With regards to the `Service is defined without a selector` message, that is correct, the master service governed by Patroni does not have a selector.

- What sequence of steps did you take to run into this error message?
- What version of Helm are you using
- What version of Kubernetes are you using?
- What is the output of:
    ```console
    kubectl get all,ep,service -l cluster-name=<deployment name>
    ```

**Comment by rleiwang** [comment]
I was trying to setup port-forward so that I can access timescalesdb from outside kubernetes for development.

I did git pull today, redeployed timescaledb-single chart. 
```
❯❯❯ kubectl get all,ep,service -l cluster-name=ktsdb -n ktsdb
NAME                      READY   STATUS    RESTARTS   AGE
pod/ktsdb-timescaledb-0   1/1     Running   0          22m
pod/ktsdb-timescaledb-1   1/1     Running   0          21m
pod/ktsdb-timescaledb-2   1/1     Running   0          20m

NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/ktsdb           LoadBalancer   10.103.171.166   <pending>     5432:31316/TCP   22m
service/ktsdb-config    ClusterIP      None             <none>        8008/TCP         22m
service/ktsdb-replica   ClusterIP      10.96.21.55      <none>        5432/TCP         22m

NAME                                 READY   AGE
statefulset.apps/ktsdb-timescaledb   3/3     22m

NAME                      ENDPOINTS                                            AGE
endpoints/ktsdb           172.17.0.10:5432                                     22m
endpoints/ktsdb-config    172.17.0.10:8008,172.17.0.15:8008,172.17.0.18:8008   22m
endpoints/ktsdb-replica   172.17.0.15:5432,172.17.0.18:5432                    22m
```
I am using Helm v3, deploy on minikube 1.3.1. The followings are the step taken. I've got a different error this time.
```
~/w/t/charts ❯❯❯ kubectl create namespace ktsdb
~/w/t/charts ❮❮❮ helm install ktsdb  timescaledb-single -n ktsdb
~/w/t/charts ❯❯❯ kubectl port-forward service/ktsdb 5432:5432 -n ktsdb
error: Pod 'ktsdb-timescaledb-0' does not have a named port 'postgresql'
```

**Comment by feikesteenbergen** [comment]
Port forwarding to the service for the primary instance is not going to work directly with `kubectl port-forward`, as it is designed to work without a selector.

More detail about this limitation of `kubectl port-forward` can be found here:

https://github.com/txn2/kubefwd/issues/35

This comment shows a possible workaround:

https://github.com/txn2/kubefwd/issues/35#issuecomment-462524408

**Comment by rleiwang** [comment]
@feikesteenbergen got it. It is as design. I just need to port forward for dev/debug purpose, I end up with port-forward port from pod directly.

```
kubectl port-forward pod/bw-timescaledb-0 5432:5432 -n test
```
