### ISSUE TITLE
Where is timescaledb-docker-ha?

### ISSUE THREAD

**Issue by allen13** [timescale/timescaledb-kubernetes#88]
Where did the ha image repo go? https://github.com/timescale/timescaledb-docker-ha

**Comment by feikesteenbergen** [comment]
It does exist, however it is currently private. Will see how we can make it public.

**Comment by allen13** [comment]
Thanks!

**Comment by rushabh-harness** [comment]
I am looking forward for this solution as well.

**Comment by feikesteenbergen** [comment]
@allen13 the https://github.com/timescale/timescaledb-docker-ha is no public.
