### ISSUE TITLE
Backrest pod is failing

### ISSUE THREAD

**Issue by ziXet** [timescale/timescaledb-kubernetes#99]
I have followed the admin guide to enable the backup and manually triggered the cronjob. The backrest pod was keep failing. I removed the --silent flag from the curl command and the error is "invalid json document". 

I saw that in this commit (https://github.com/timescale/timescaledb-kubernetes/commit/6e2ea58702f7b42cfe33cee9750890340898a5b9?diff=unified) the wget is replaced by curl. i reverted back the cmd to wget but now, the backup server which is listening to port 8081 return "Internal Server Error"

**Comment by feikesteenbergen** [comment]
This is probably fixed with #101, could you verify that?

**Comment by ziXet** [comment]
Yes, it's fixed.
